"use client";

import * as React from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Copy, CheckCircle2, Download, FileText } from "lucide-react";

interface OutputViewProps {
    isOpen: boolean;
    onOpenChange: (open: boolean) => void;
    soapNotes?: string | {
        subjective?: string;
        objective?: string;
        assessment?: string;
        plan?: string;
    };
}

export function OutputView({ isOpen, onOpenChange, soapNotes }: OutputViewProps) {
    const [isCopied, setIsCopied] = React.useState(false);

    const getNoteString = () => {
        if (!soapNotes) return "";
        if (typeof soapNotes === "string") return soapNotes;

        return `SUBJECTIVE:\n${soapNotes.subjective || ""}\n\nOBJECTIVE:\n${soapNotes.objective || ""}\n\nASSESSMENT:\n${soapNotes.assessment || ""}\n\nPLAN:\n${soapNotes.plan || ""}`;
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(getNoteString());
        setIsCopied(true);
        setTimeout(() => setIsCopied(false), 2000);
    };

    const handleDownload = () => {
        const element = document.createElement("a");
        const file = new Blob([getNoteString()], { type: 'text/plain' });
        element.href = URL.createObjectURL(file);
        element.download = `SOAP_Note_${new Date().toISOString().split('T')[0]}.txt`;
        document.body.appendChild(element);
        element.click();
        document.body.removeChild(element);
    };

    return (
        <Dialog open={isOpen} onOpenChange={onOpenChange}>
            <DialogContent className="sm:max-w-[800px] max-h-[90vh] flex flex-col p-0 overflow-hidden">
                <DialogHeader className="px-6 py-4 border-b flex flex-row items-center justify-between space-y-0">
                    <DialogTitle className="flex items-center gap-2">
                        <FileText className="h-5 w-5 text-primary" />
                        Clinical Documentation Draft
                    </DialogTitle>
                    <div className="flex gap-2 mr-8">
                        <Button variant="outline" size="sm" onClick={handleCopy} className="h-8 gap-2">
                            {isCopied ? (
                                <><CheckCircle2 className="h-3.5 w-3.5 text-green-500" /> Copied</>
                            ) : (
                                <><Copy className="h-3.5 w-3.5" /> Copy</>
                            )}
                        </Button>
                        <Button variant="outline" size="sm" onClick={handleDownload} className="h-8 gap-2">
                            <Download className="h-3.5 w-3.5" /> Download
                        </Button>
                    </div>
                </DialogHeader>

                <ScrollArea className="flex-1 p-6 bg-slate-50 dark:bg-zinc-950">
                    {soapNotes ? (
                        typeof soapNotes === "object" ? (
                            <div className="bg-white dark:bg-zinc-900 border shadow-sm rounded-sm p-8 space-y-8 max-w-2xl mx-auto text-sm leading-relaxed">
                                <div className="text-center border-b pb-6 mb-8">
                                    <h2 className="text-xl font-bold uppercase tracking-widest text-primary">Psychiatric SOAP Note</h2>
                                    <p className="text-xs text-muted-foreground mt-1">Generated by Crucible Agent Mesh</p>
                                </div>

                                <section className="space-y-3">
                                    <h4 className="font-bold text-xs uppercase tracking-[0.2em] text-primary/80 border-b pb-1">Subjective</h4>
                                    <div className="text-slate-700 dark:text-slate-300 whitespace-pre-wrap pl-2 border-l-2 border-slate-100 dark:border-slate-800">
                                        {soapNotes.subjective || "No subjective data."}
                                    </div>
                                </section>

                                <section className="space-y-3">
                                    <h4 className="font-bold text-xs uppercase tracking-[0.2em] text-primary/80 border-b pb-1">Objective</h4>
                                    <div className="text-slate-700 dark:text-slate-300 whitespace-pre-wrap pl-2 border-l-2 border-slate-100 dark:border-slate-800">
                                        {soapNotes.objective || "No objective data."}
                                    </div>
                                </section>

                                <section className="space-y-3">
                                    <h4 className="font-bold text-xs uppercase tracking-[0.2em] text-primary/80 border-b pb-1">Assessment</h4>
                                    <div className="text-slate-700 dark:text-slate-300 whitespace-pre-wrap pl-2 border-l-2 border-slate-100 dark:border-slate-800">
                                        {soapNotes.assessment || "No assessment data."}
                                    </div>
                                </section>

                                <section className="space-y-3">
                                    <h4 className="font-bold text-xs uppercase tracking-[0.2em] text-primary/80 border-b pb-1">Plan</h4>
                                    <div className="text-slate-700 dark:text-slate-300 whitespace-pre-wrap pl-2 border-l-2 border-slate-100 dark:border-slate-800">
                                        {soapNotes.plan || "No plan data."}
                                    </div>
                                </section>

                                <div className="pt-10 mt-10 border-t text-[10px] text-muted-foreground italic flex justify-between">
                                    <span>Electronic Signature: AI-Generated Draft</span>
                                    <span>Date: {new Date().toLocaleDateString()}</span>
                                </div>
                            </div>
                        ) : (
                            <div className="bg-white dark:bg-zinc-900 border shadow-sm rounded-sm p-8 max-w-2xl mx-auto whitespace-pre-wrap text-sm">
                                {soapNotes}
                            </div>
                        )
                    ) : (
                        <div className="h-64 flex flex-col items-center justify-center text-center space-y-4">
                            <div className="w-16 h-16 bg-muted rounded-full flex items-center justify-center opacity-20">
                                <FileText className="h-8 w-8" />
                            </div>
                            <p className="text-muted-foreground max-w-xs mx-auto text-sm">
                                No documentation generated yet. The AI team will populate this draft as the analysis completes.
                            </p>
                        </div>
                    )}
                </ScrollArea>
                <DialogFooter className="px-6 py-4 border-t bg-white dark:bg-zinc-900">
                    <Button onClick={() => onOpenChange(false)}>Close View</Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
